
include(${CMAKE_CURRENT_LIST_DIR}/../stm32_config.cmake)

set(LDSCRIPT ${CMAKE_CURRENT_LIST_DIR}/STM32F103XB_FLASH.ld)

set(MCU STM32F103C8)

list(APPEND LIBS stm32f1)

list(APPEND DEFINES STM32)
